changelog:
  exclude:
    authors:
      # Excludes automated dependency updates for GitHub workflows, as these are not AppLauncher dependencies and are not relevant for the changelog.
      - dependabot[bot]
