name: CD

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to publish artifacts for"
        required: true
  release:
    types:
      - published

permissions: {} # No permissions are granted at the workflow level

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set TAG_NAME
        id: vars
        run: |
          echo "TAG_NAME=${{ github.event.release.tag_name || inputs.tag }}" >> $GITHUB_OUTPUT

      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # Required to resolve tag commits

      - name: Resolve commit SHA for tag
        id: resolve_sha
        run: |
          COMMIT_SHA=$(git rev-list -n 1 $TAG_NAME)
          echo "COMMIT_SHA [$COMMIT_SHA]"
          echo "commit-sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
        env:
          TAG_NAME: ${{ steps.vars.outputs.TAG_NAME }}

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@b6e2e70617bc3265edd6dab6c906732b2f1ae151 # v21
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: CI.yml
          workflow_conclusion: success
          commit: ${{ steps.resolve_sha.outputs.commit-sha }}
          repo: ${{ github.repository }}
          name: ".+-packages"
          name_is_regexp: true

      - name: List downloaded files
        run: ls -1 -R *-packages

      - name: Upload release assets
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          tag_name: ${{ steps.vars.outputs.TAG_NAME }}
          files: |
            *-packages/CTKAppLauncher-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.COMMONTKBOT_GITHUB_TOKEN }}
